language: cpp
compiler:
 - clang
 - gcc
install: 
branches:
 only:
  - test
notifications:
 recipients:
  - asmodehn@gmail.com
 email:
  on_success: change
  on_failure: always
script: "./build.sh"

  